name: sahayatri
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Downgraded to be compatible with Dart 3.4.3
  flutter_launcher_icons: "^0.14.1"  # Added for generating app icons

flutter:
  uses-material-design: true

  # Add assets for the app
  assets:
    - assets/bus.png

flutter_icons:
  android: true           # Set to true to generate icons for Android
  ios: false              # Set to false if you don't need iOS icons
  image_path: "assets/icon/final.png"  # Path to your app icon image
