name: sahayatri
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.14.1"  # Add this line to include the flutter_launcher_icons dependency

flutter:
  uses-material-design: true

  # Add assets for the app
  assets:
    - assets/bus.png

flutter_icons:
  android: true           # Set to true to generate icons for Android
  ios: false              # Set to false if you don't need iOS icons
  image_path: "assets/icon/final.png"  # Path to your app icon image
